version: '3'
services:
  app:
    build: ./php
    container_name: php
    volumes:
      - ../:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PASS=root_pass

  web:
    build: ./nginx
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro

  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./.data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
